name: Build the app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      -master
  schedule:
    - cron: '0 0 15 * *'

jobs:
  build:
    name: Build and upload the generated apk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Bake
        path: app/build/outputs/apk/debug/app-debug.apk
